/* This file was generated by SableCC (http://www.sablecc.org/). */

package lyrics.sablecc.analysis;

import lyrics.sablecc.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAConMetaArchivo(AConMetaArchivo node);
    void caseASinMetaArchivo(ASinMetaArchivo node);
    void caseAUnoMetadata(AUnoMetadata node);
    void caseAVariosMetadata(AVariosMetadata node);
    void caseAArMetaTag(AArMetaTag node);
    void caseATiMetaTag(ATiMetaTag node);
    void caseAAlMetaTag(AAlMetaTag node);
    void caseAOtroMetaTag(AOtroMetaTag node);
    void caseAUnaLineas(AUnaLineas node);
    void caseAVariasLineas(AVariasLineas node);
    void caseAConTextoLinea(AConTextoLinea node);
    void caseAVaciaLinea(AVaciaLinea node);

    void caseTBlanco(TBlanco node);
    void caseTFdlin(TFdlin node);
    void caseTTiempoTag(TTiempoTag node);
    void caseTTagArtista(TTagArtista node);
    void caseTTagTitulo(TTagTitulo node);
    void caseTTagAlbum(TTagAlbum node);
    void caseTTagOtro(TTagOtro node);
    void caseTTextoLirica(TTextoLirica node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
