/* This file was generated by SableCC (http://www.sablecc.org/). */

package lyrics.sablecc.analysis;

import java.util.*;
import lyrics.sablecc.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    @Override
    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    @Override
    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    @Override
    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    @Override
    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    @Override
    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAConMetaArchivo(AConMetaArchivo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASinMetaArchivo(ASinMetaArchivo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAUnoMetadata(AUnoMetadata node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVariosMetadata(AVariosMetadata node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAArMetaTag(AArMetaTag node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATiMetaTag(ATiMetaTag node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAlMetaTag(AAlMetaTag node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAOtroMetaTag(AOtroMetaTag node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAUnaLineas(AUnaLineas node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVariasLineas(AVariasLineas node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAConTextoLinea(AConTextoLinea node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVaciaLinea(AVaciaLinea node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBlanco(TBlanco node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFdlin(TFdlin node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTiempoTag(TTiempoTag node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTagArtista(TTagArtista node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTagTitulo(TTagTitulo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTagAlbum(TTagAlbum node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTagOtro(TTagOtro node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTextoLirica(TTextoLirica node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMarcaBom(TMarcaBom node)
    {
        defaultCase(node);
    }

    @Override
    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    @Override
    public void caseInvalidToken(InvalidToken node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
