/* This file was generated by SableCC (http://www.sablecc.org/). */

package lyrics.sablecc.analysis;

import java.util.*;
import lyrics.sablecc.node.*;

public class ReversedDepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getEOF().apply(this);
        node.getPArchivo().apply(this);
        outStart(node);
    }

    public void inAConMetaArchivo(AConMetaArchivo node)
    {
        defaultIn(node);
    }

    public void outAConMetaArchivo(AConMetaArchivo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAConMetaArchivo(AConMetaArchivo node)
    {
        inAConMetaArchivo(node);
        if(node.getLineas() != null)
        {
            node.getLineas().apply(this);
        }
        if(node.getMetadata() != null)
        {
            node.getMetadata().apply(this);
        }
        outAConMetaArchivo(node);
    }

    public void inASinMetaArchivo(ASinMetaArchivo node)
    {
        defaultIn(node);
    }

    public void outASinMetaArchivo(ASinMetaArchivo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASinMetaArchivo(ASinMetaArchivo node)
    {
        inASinMetaArchivo(node);
        if(node.getLineas() != null)
        {
            node.getLineas().apply(this);
        }
        outASinMetaArchivo(node);
    }

    public void inAUnoMetadata(AUnoMetadata node)
    {
        defaultIn(node);
    }

    public void outAUnoMetadata(AUnoMetadata node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnoMetadata(AUnoMetadata node)
    {
        inAUnoMetadata(node);
        if(node.getMetaTag() != null)
        {
            node.getMetaTag().apply(this);
        }
        outAUnoMetadata(node);
    }

    public void inAVariosMetadata(AVariosMetadata node)
    {
        defaultIn(node);
    }

    public void outAVariosMetadata(AVariosMetadata node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVariosMetadata(AVariosMetadata node)
    {
        inAVariosMetadata(node);
        if(node.getMetadata() != null)
        {
            node.getMetadata().apply(this);
        }
        if(node.getMetaTag() != null)
        {
            node.getMetaTag().apply(this);
        }
        outAVariosMetadata(node);
    }

    public void inAArMetaTag(AArMetaTag node)
    {
        defaultIn(node);
    }

    public void outAArMetaTag(AArMetaTag node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAArMetaTag(AArMetaTag node)
    {
        inAArMetaTag(node);
        if(node.getTagArtista() != null)
        {
            node.getTagArtista().apply(this);
        }
        outAArMetaTag(node);
    }

    public void inATiMetaTag(ATiMetaTag node)
    {
        defaultIn(node);
    }

    public void outATiMetaTag(ATiMetaTag node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATiMetaTag(ATiMetaTag node)
    {
        inATiMetaTag(node);
        if(node.getTagTitulo() != null)
        {
            node.getTagTitulo().apply(this);
        }
        outATiMetaTag(node);
    }

    public void inAAlMetaTag(AAlMetaTag node)
    {
        defaultIn(node);
    }

    public void outAAlMetaTag(AAlMetaTag node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAlMetaTag(AAlMetaTag node)
    {
        inAAlMetaTag(node);
        if(node.getTagAlbum() != null)
        {
            node.getTagAlbum().apply(this);
        }
        outAAlMetaTag(node);
    }

    public void inAOtroMetaTag(AOtroMetaTag node)
    {
        defaultIn(node);
    }

    public void outAOtroMetaTag(AOtroMetaTag node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOtroMetaTag(AOtroMetaTag node)
    {
        inAOtroMetaTag(node);
        if(node.getTagOtro() != null)
        {
            node.getTagOtro().apply(this);
        }
        outAOtroMetaTag(node);
    }

    public void inAUnaLineas(AUnaLineas node)
    {
        defaultIn(node);
    }

    public void outAUnaLineas(AUnaLineas node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnaLineas(AUnaLineas node)
    {
        inAUnaLineas(node);
        if(node.getLinea() != null)
        {
            node.getLinea().apply(this);
        }
        outAUnaLineas(node);
    }

    public void inAVariasLineas(AVariasLineas node)
    {
        defaultIn(node);
    }

    public void outAVariasLineas(AVariasLineas node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVariasLineas(AVariasLineas node)
    {
        inAVariasLineas(node);
        if(node.getLineas() != null)
        {
            node.getLineas().apply(this);
        }
        if(node.getLinea() != null)
        {
            node.getLinea().apply(this);
        }
        outAVariasLineas(node);
    }

    public void inAConTextoLinea(AConTextoLinea node)
    {
        defaultIn(node);
    }

    public void outAConTextoLinea(AConTextoLinea node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAConTextoLinea(AConTextoLinea node)
    {
        inAConTextoLinea(node);
        if(node.getTextoLirica() != null)
        {
            node.getTextoLirica().apply(this);
        }
        if(node.getTiempoTag() != null)
        {
            node.getTiempoTag().apply(this);
        }
        outAConTextoLinea(node);
    }

    public void inAVaciaLinea(AVaciaLinea node)
    {
        defaultIn(node);
    }

    public void outAVaciaLinea(AVaciaLinea node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVaciaLinea(AVaciaLinea node)
    {
        inAVaciaLinea(node);
        if(node.getTiempoTag() != null)
        {
            node.getTiempoTag().apply(this);
        }
        outAVaciaLinea(node);
    }
}
