/* This file was generated by SableCC (http://www.sablecc.org/). */

package lyrics.sablecc.node;

import lyrics.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AAlMetaTag extends PMetaTag
{
    private TTagAlbum _tagAlbum_;

    public AAlMetaTag()
    {
        // Constructor
    }

    public AAlMetaTag(
        @SuppressWarnings("hiding") TTagAlbum _tagAlbum_)
    {
        // Constructor
        setTagAlbum(_tagAlbum_);

    }

    @Override
    public Object clone()
    {
        return new AAlMetaTag(
            cloneNode(this._tagAlbum_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAlMetaTag(this);
    }

    public TTagAlbum getTagAlbum()
    {
        return this._tagAlbum_;
    }

    public void setTagAlbum(TTagAlbum node)
    {
        if(this._tagAlbum_ != null)
        {
            this._tagAlbum_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tagAlbum_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tagAlbum_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tagAlbum_ == child)
        {
            this._tagAlbum_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tagAlbum_ == oldChild)
        {
            setTagAlbum((TTagAlbum) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
