/* This file was generated by SableCC (http://www.sablecc.org/). */

package lyrics.sablecc.node;

import lyrics.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AArMetaTag extends PMetaTag
{
    private TTagArtista _tagArtista_;

    public AArMetaTag()
    {
        // Constructor
    }

    public AArMetaTag(
        @SuppressWarnings("hiding") TTagArtista _tagArtista_)
    {
        // Constructor
        setTagArtista(_tagArtista_);

    }

    @Override
    public Object clone()
    {
        return new AArMetaTag(
            cloneNode(this._tagArtista_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArMetaTag(this);
    }

    public TTagArtista getTagArtista()
    {
        return this._tagArtista_;
    }

    public void setTagArtista(TTagArtista node)
    {
        if(this._tagArtista_ != null)
        {
            this._tagArtista_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tagArtista_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tagArtista_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tagArtista_ == child)
        {
            this._tagArtista_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tagArtista_ == oldChild)
        {
            setTagArtista((TTagArtista) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
