/* This file was generated by SableCC (http://www.sablecc.org/). */

package lyrics.sablecc.node;

import lyrics.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AConTextoLinea extends PLinea
{
    private PTiempoTag _tiempoTag_;
    private TTextoLirica _textoLirica_;

    public AConTextoLinea()
    {
        // Constructor
    }

    public AConTextoLinea(
        @SuppressWarnings("hiding") PTiempoTag _tiempoTag_,
        @SuppressWarnings("hiding") TTextoLirica _textoLirica_)
    {
        // Constructor
        setTiempoTag(_tiempoTag_);

        setTextoLirica(_textoLirica_);

    }

    @Override
    public Object clone()
    {
        return new AConTextoLinea(
            cloneNode(this._tiempoTag_),
            cloneNode(this._textoLirica_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConTextoLinea(this);
    }

    public PTiempoTag getTiempoTag()
    {
        return this._tiempoTag_;
    }

    public void setTiempoTag(PTiempoTag node)
    {
        if(this._tiempoTag_ != null)
        {
            this._tiempoTag_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tiempoTag_ = node;
    }

    public TTextoLirica getTextoLirica()
    {
        return this._textoLirica_;
    }

    public void setTextoLirica(TTextoLirica node)
    {
        if(this._textoLirica_ != null)
        {
            this._textoLirica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._textoLirica_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tiempoTag_)
            + toString(this._textoLirica_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tiempoTag_ == child)
        {
            this._tiempoTag_ = null;
            return;
        }

        if(this._textoLirica_ == child)
        {
            this._textoLirica_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tiempoTag_ == oldChild)
        {
            setTiempoTag((PTiempoTag) newChild);
            return;
        }

        if(this._textoLirica_ == oldChild)
        {
            setTextoLirica((TTextoLirica) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
