/* This file was generated by SableCC (http://www.sablecc.org/). */

package lyrics.sablecc.node;

import lyrics.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AConMetaArchivo extends PArchivo
{
    private PMetadata _metadata_;
    private PLineas _lineas_;

    public AConMetaArchivo()
    {
        // Constructor
    }

    public AConMetaArchivo(
        @SuppressWarnings("hiding") PMetadata _metadata_,
        @SuppressWarnings("hiding") PLineas _lineas_)
    {
        // Constructor
        setMetadata(_metadata_);

        setLineas(_lineas_);

    }

    @Override
    public Object clone()
    {
        return new AConMetaArchivo(
            cloneNode(this._metadata_),
            cloneNode(this._lineas_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConMetaArchivo(this);
    }

    public PMetadata getMetadata()
    {
        return this._metadata_;
    }

    public void setMetadata(PMetadata node)
    {
        if(this._metadata_ != null)
        {
            this._metadata_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._metadata_ = node;
    }

    public PLineas getLineas()
    {
        return this._lineas_;
    }

    public void setLineas(PLineas node)
    {
        if(this._lineas_ != null)
        {
            this._lineas_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lineas_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._metadata_)
            + toString(this._lineas_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._metadata_ == child)
        {
            this._metadata_ = null;
            return;
        }

        if(this._lineas_ == child)
        {
            this._lineas_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._metadata_ == oldChild)
        {
            setMetadata((PMetadata) newChild);
            return;
        }

        if(this._lineas_ == oldChild)
        {
            setLineas((PLineas) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
