/* This file was generated by SableCC (http://www.sablecc.org/). */

package lyrics.sablecc.node;

import lyrics.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AOtroMetaTag extends PMetaTag
{
    private TTagOtro _tagOtro_;

    public AOtroMetaTag()
    {
        // Constructor
    }

    public AOtroMetaTag(
        @SuppressWarnings("hiding") TTagOtro _tagOtro_)
    {
        // Constructor
        setTagOtro(_tagOtro_);

    }

    @Override
    public Object clone()
    {
        return new AOtroMetaTag(
            cloneNode(this._tagOtro_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOtroMetaTag(this);
    }

    public TTagOtro getTagOtro()
    {
        return this._tagOtro_;
    }

    public void setTagOtro(TTagOtro node)
    {
        if(this._tagOtro_ != null)
        {
            this._tagOtro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tagOtro_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tagOtro_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tagOtro_ == child)
        {
            this._tagOtro_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tagOtro_ == oldChild)
        {
            setTagOtro((TTagOtro) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
