/* This file was generated by SableCC (http://www.sablecc.org/). */

package lyrics.sablecc.node;

import lyrics.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ASinMetaArchivo extends PArchivo
{
    private PLineas _lineas_;

    public ASinMetaArchivo()
    {
        // Constructor
    }

    public ASinMetaArchivo(
        @SuppressWarnings("hiding") PLineas _lineas_)
    {
        // Constructor
        setLineas(_lineas_);

    }

    @Override
    public Object clone()
    {
        return new ASinMetaArchivo(
            cloneNode(this._lineas_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASinMetaArchivo(this);
    }

    public PLineas getLineas()
    {
        return this._lineas_;
    }

    public void setLineas(PLineas node)
    {
        if(this._lineas_ != null)
        {
            this._lineas_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lineas_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lineas_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lineas_ == child)
        {
            this._lineas_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lineas_ == oldChild)
        {
            setLineas((PLineas) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
