/* This file was generated by SableCC (http://www.sablecc.org/). */

package lyrics.sablecc.node;

import lyrics.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ATiempoTag extends PTiempoTag
{
    private TCorcheteIzq _corcheteIzq_;
    private TNumero _minutos_;
    private TDosPuntos _dosPuntos_;
    private TNumero _segundos_;
    private TPunto _punto_;
    private TNumero _centesimas_;
    private TCorcheteDer _corcheteDer_;

    public ATiempoTag()
    {
        // Constructor
    }

    public ATiempoTag(
        @SuppressWarnings("hiding") TCorcheteIzq _corcheteIzq_,
        @SuppressWarnings("hiding") TNumero _minutos_,
        @SuppressWarnings("hiding") TDosPuntos _dosPuntos_,
        @SuppressWarnings("hiding") TNumero _segundos_,
        @SuppressWarnings("hiding") TPunto _punto_,
        @SuppressWarnings("hiding") TNumero _centesimas_,
        @SuppressWarnings("hiding") TCorcheteDer _corcheteDer_)
    {
        // Constructor
        setCorcheteIzq(_corcheteIzq_);

        setMinutos(_minutos_);

        setDosPuntos(_dosPuntos_);

        setSegundos(_segundos_);

        setPunto(_punto_);

        setCentesimas(_centesimas_);

        setCorcheteDer(_corcheteDer_);

    }

    @Override
    public Object clone()
    {
        return new ATiempoTag(
            cloneNode(this._corcheteIzq_),
            cloneNode(this._minutos_),
            cloneNode(this._dosPuntos_),
            cloneNode(this._segundos_),
            cloneNode(this._punto_),
            cloneNode(this._centesimas_),
            cloneNode(this._corcheteDer_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATiempoTag(this);
    }

    public TCorcheteIzq getCorcheteIzq()
    {
        return this._corcheteIzq_;
    }

    public void setCorcheteIzq(TCorcheteIzq node)
    {
        if(this._corcheteIzq_ != null)
        {
            this._corcheteIzq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._corcheteIzq_ = node;
    }

    public TNumero getMinutos()
    {
        return this._minutos_;
    }

    public void setMinutos(TNumero node)
    {
        if(this._minutos_ != null)
        {
            this._minutos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minutos_ = node;
    }

    public TDosPuntos getDosPuntos()
    {
        return this._dosPuntos_;
    }

    public void setDosPuntos(TDosPuntos node)
    {
        if(this._dosPuntos_ != null)
        {
            this._dosPuntos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dosPuntos_ = node;
    }

    public TNumero getSegundos()
    {
        return this._segundos_;
    }

    public void setSegundos(TNumero node)
    {
        if(this._segundos_ != null)
        {
            this._segundos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._segundos_ = node;
    }

    public TPunto getPunto()
    {
        return this._punto_;
    }

    public void setPunto(TPunto node)
    {
        if(this._punto_ != null)
        {
            this._punto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._punto_ = node;
    }

    public TNumero getCentesimas()
    {
        return this._centesimas_;
    }

    public void setCentesimas(TNumero node)
    {
        if(this._centesimas_ != null)
        {
            this._centesimas_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._centesimas_ = node;
    }

    public TCorcheteDer getCorcheteDer()
    {
        return this._corcheteDer_;
    }

    public void setCorcheteDer(TCorcheteDer node)
    {
        if(this._corcheteDer_ != null)
        {
            this._corcheteDer_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._corcheteDer_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._corcheteIzq_)
            + toString(this._minutos_)
            + toString(this._dosPuntos_)
            + toString(this._segundos_)
            + toString(this._punto_)
            + toString(this._centesimas_)
            + toString(this._corcheteDer_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._corcheteIzq_ == child)
        {
            this._corcheteIzq_ = null;
            return;
        }

        if(this._minutos_ == child)
        {
            this._minutos_ = null;
            return;
        }

        if(this._dosPuntos_ == child)
        {
            this._dosPuntos_ = null;
            return;
        }

        if(this._segundos_ == child)
        {
            this._segundos_ = null;
            return;
        }

        if(this._punto_ == child)
        {
            this._punto_ = null;
            return;
        }

        if(this._centesimas_ == child)
        {
            this._centesimas_ = null;
            return;
        }

        if(this._corcheteDer_ == child)
        {
            this._corcheteDer_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._corcheteIzq_ == oldChild)
        {
            setCorcheteIzq((TCorcheteIzq) newChild);
            return;
        }

        if(this._minutos_ == oldChild)
        {
            setMinutos((TNumero) newChild);
            return;
        }

        if(this._dosPuntos_ == oldChild)
        {
            setDosPuntos((TDosPuntos) newChild);
            return;
        }

        if(this._segundos_ == oldChild)
        {
            setSegundos((TNumero) newChild);
            return;
        }

        if(this._punto_ == oldChild)
        {
            setPunto((TPunto) newChild);
            return;
        }

        if(this._centesimas_ == oldChild)
        {
            setCentesimas((TNumero) newChild);
            return;
        }

        if(this._corcheteDer_ == oldChild)
        {
            setCorcheteDer((TCorcheteDer) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
