/* This file was generated by SableCC (http://www.sablecc.org/). */

package lyrics.sablecc.node;

import lyrics.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ATiMetaTag extends PMetaTag
{
    private TTagTitulo _tagTitulo_;

    public ATiMetaTag()
    {
        // Constructor
    }

    public ATiMetaTag(
        @SuppressWarnings("hiding") TTagTitulo _tagTitulo_)
    {
        // Constructor
        setTagTitulo(_tagTitulo_);

    }

    @Override
    public Object clone()
    {
        return new ATiMetaTag(
            cloneNode(this._tagTitulo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATiMetaTag(this);
    }

    public TTagTitulo getTagTitulo()
    {
        return this._tagTitulo_;
    }

    public void setTagTitulo(TTagTitulo node)
    {
        if(this._tagTitulo_ != null)
        {
            this._tagTitulo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tagTitulo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tagTitulo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tagTitulo_ == child)
        {
            this._tagTitulo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tagTitulo_ == oldChild)
        {
            setTagTitulo((TTagTitulo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
