/* This file was generated by SableCC (http://www.sablecc.org/). */

package lyrics.sablecc.node;

import lyrics.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AUnaLineas extends PLineas
{
    private PLinea _linea_;

    public AUnaLineas()
    {
        // Constructor
    }

    public AUnaLineas(
        @SuppressWarnings("hiding") PLinea _linea_)
    {
        // Constructor
        setLinea(_linea_);

    }

    @Override
    public Object clone()
    {
        return new AUnaLineas(
            cloneNode(this._linea_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUnaLineas(this);
    }

    public PLinea getLinea()
    {
        return this._linea_;
    }

    public void setLinea(PLinea node)
    {
        if(this._linea_ != null)
        {
            this._linea_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._linea_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._linea_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._linea_ == child)
        {
            this._linea_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._linea_ == oldChild)
        {
            setLinea((PLinea) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
