/* This file was generated by SableCC (http://www.sablecc.org/). */

package lyrics.sablecc.node;

import lyrics.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AUnoMetadata extends PMetadata
{
    private PMetaTag _metaTag_;

    public AUnoMetadata()
    {
        // Constructor
    }

    public AUnoMetadata(
        @SuppressWarnings("hiding") PMetaTag _metaTag_)
    {
        // Constructor
        setMetaTag(_metaTag_);

    }

    @Override
    public Object clone()
    {
        return new AUnoMetadata(
            cloneNode(this._metaTag_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUnoMetadata(this);
    }

    public PMetaTag getMetaTag()
    {
        return this._metaTag_;
    }

    public void setMetaTag(PMetaTag node)
    {
        if(this._metaTag_ != null)
        {
            this._metaTag_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._metaTag_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._metaTag_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._metaTag_ == child)
        {
            this._metaTag_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._metaTag_ == oldChild)
        {
            setMetaTag((PMetaTag) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
