/* This file was generated by SableCC (http://www.sablecc.org/). */

package lyrics.sablecc.node;

import lyrics.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AVaciaLinea extends PLinea
{
    private PTiempoTag _tiempoTag_;

    public AVaciaLinea()
    {
        // Constructor
    }

    public AVaciaLinea(
        @SuppressWarnings("hiding") PTiempoTag _tiempoTag_)
    {
        // Constructor
        setTiempoTag(_tiempoTag_);

    }

    @Override
    public Object clone()
    {
        return new AVaciaLinea(
            cloneNode(this._tiempoTag_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVaciaLinea(this);
    }

    public PTiempoTag getTiempoTag()
    {
        return this._tiempoTag_;
    }

    public void setTiempoTag(PTiempoTag node)
    {
        if(this._tiempoTag_ != null)
        {
            this._tiempoTag_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tiempoTag_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tiempoTag_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tiempoTag_ == child)
        {
            this._tiempoTag_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tiempoTag_ == oldChild)
        {
            setTiempoTag((PTiempoTag) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
