/* This file was generated by SableCC (http://www.sablecc.org/). */

package lyrics.sablecc.node;

import lyrics.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AVariasLineas extends PLineas
{
    private PLinea _linea_;
    private PLineas _lineas_;

    public AVariasLineas()
    {
        // Constructor
    }

    public AVariasLineas(
        @SuppressWarnings("hiding") PLinea _linea_,
        @SuppressWarnings("hiding") PLineas _lineas_)
    {
        // Constructor
        setLinea(_linea_);

        setLineas(_lineas_);

    }

    @Override
    public Object clone()
    {
        return new AVariasLineas(
            cloneNode(this._linea_),
            cloneNode(this._lineas_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariasLineas(this);
    }

    public PLinea getLinea()
    {
        return this._linea_;
    }

    public void setLinea(PLinea node)
    {
        if(this._linea_ != null)
        {
            this._linea_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._linea_ = node;
    }

    public PLineas getLineas()
    {
        return this._lineas_;
    }

    public void setLineas(PLineas node)
    {
        if(this._lineas_ != null)
        {
            this._lineas_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lineas_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._linea_)
            + toString(this._lineas_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._linea_ == child)
        {
            this._linea_ = null;
            return;
        }

        if(this._lineas_ == child)
        {
            this._lineas_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._linea_ == oldChild)
        {
            setLinea((PLinea) newChild);
            return;
        }

        if(this._lineas_ == oldChild)
        {
            setLineas((PLineas) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
