/* This file was generated by SableCC (http://www.sablecc.org/). */

package lyrics.sablecc.node;

import lyrics.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AVariosMetadata extends PMetadata
{
    private PMetaTag _metaTag_;
    private PMetadata _metadata_;

    public AVariosMetadata()
    {
        // Constructor
    }

    public AVariosMetadata(
        @SuppressWarnings("hiding") PMetaTag _metaTag_,
        @SuppressWarnings("hiding") PMetadata _metadata_)
    {
        // Constructor
        setMetaTag(_metaTag_);

        setMetadata(_metadata_);

    }

    @Override
    public Object clone()
    {
        return new AVariosMetadata(
            cloneNode(this._metaTag_),
            cloneNode(this._metadata_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariosMetadata(this);
    }

    public PMetaTag getMetaTag()
    {
        return this._metaTag_;
    }

    public void setMetaTag(PMetaTag node)
    {
        if(this._metaTag_ != null)
        {
            this._metaTag_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._metaTag_ = node;
    }

    public PMetadata getMetadata()
    {
        return this._metadata_;
    }

    public void setMetadata(PMetadata node)
    {
        if(this._metadata_ != null)
        {
            this._metadata_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._metadata_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._metaTag_)
            + toString(this._metadata_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._metaTag_ == child)
        {
            this._metaTag_ = null;
            return;
        }

        if(this._metadata_ == child)
        {
            this._metadata_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._metaTag_ == oldChild)
        {
            setMetaTag((PMetaTag) newChild);
            return;
        }

        if(this._metadata_ == oldChild)
        {
            setMetadata((PMetadata) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
