/* This file was generated by SableCC (http://www.sablecc.org/). */

package lyrics.sablecc.node;

import lyrics.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TBlanco extends Token
{
    public TBlanco(String text)
    {
        setText(text);
    }

    public TBlanco(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TBlanco(getText(), getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTBlanco(this);
    }
}
