/* This file was generated by SableCC (http://www.sablecc.org/). */

package lyrics.sablecc.node;

import lyrics.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TCorcheteDer extends Token
{
    public TCorcheteDer()
    {
        super.setText("]");
    }

    public TCorcheteDer(int line, int pos)
    {
        super.setText("]");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCorcheteDer(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCorcheteDer(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCorcheteDer text.");
    }
}
