/* This file was generated by SableCC (http://www.sablecc.org/). */

package lyrics.sablecc.node;

import lyrics.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TPunto extends Token
{
    public TPunto()
    {
        super.setText(".");
    }

    public TPunto(int line, int pos)
    {
        super.setText(".");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPunto(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPunto(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPunto text.");
    }
}
